# Generated by Django 4.2 on 2023-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='Default Value'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='Default Value'),
        ),
    ]
